language: java
after_success:
  - codecov -f target/site/*
services:
  - postgresql
before_script:
  - psql -c "create database postgres;" -U postgres // your database name
  - sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'postgres'"