POST http://localhost:8080/myapp/api/register?username=Brain&password=123&firstName=Brayan&lastName=Tuesday&email=braineee@gmail.com
Accept: application/json
Cache-Control: no-cache

###

GET http://localhost:8080/myapp/api/auth?username=Brain&password=123
Accept: */*
Cache-Control: no-cache

###