POST http://localhost:8080/myapp/api/register?username=Arthur2&password=123&firstName=Arthur&lastName=Kupriyanov&email=apploidyakutsk@gmail.com
Accept: application/json

GET http://localhost:8080/myapp/api/auth?username=Arthur2&password=123
Cache-Control: no-cache

###